_wandb:
    value:
        cli_version: 0.24.2
        e:
            62r9aufxzbz7jtgchp3d2zn9lu1pbfzd:
                args:
                    - --s3_bucket
                    - furniture-clip-dataset-v1
                    - --s3_prefix
                    - dataset-clip/
                    - --mini_train
                    - --scenario
                    - dual_lora
                    - --micro_batch_size
                    - "32"
                    - --wandb_project
                    - clip-lr-finder
                codePath: src/training/main.py
                codePathLocal: src/training/main.py
                cpu_count: 1
                cpu_count_logical: 2
                disk:
                    /:
                        total: "33636024320"
                        used: "20497842176"
                email: nessi.victor@gmail.com
                executable: /home/codespace/.python/current/bin/python
                git:
                    commit: a7fdbc856a1bd4618504f2cdcd1d82ec016c612f
                    remote: https://github.com/nectorv/CLIP_Fine_Tuning
                host: codespaces-d9ae48
                memory:
                    total: "8329543680"
                os: Linux-6.8.0-1030-azure-x86_64-with-glibc2.39
                program: /workspaces/CLIP_Fine_Tuning/src/training/main.py
                python: CPython 3.12.1
                root: /workspaces/CLIP_Fine_Tuning
                startedAt: "2026-02-09T12:57:44.445847Z"
                writerId: 62r9aufxzbz7jtgchp3d2zn9lu1pbfzd
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 98
            "3":
                - 13
                - 16
            "4": 3.12.1
            "5": 0.24.2
            "6": 4.57.6
            "12": 0.24.2
            "13": linux-x86_64
augmentation:
    value: simple
data_dir:
    value: /tmp/furniture_data
effective_batch_size:
    value: 1024
epochs:
    value: 10
grad_clip:
    value: 1
lora_alpha:
    value: 32
lora_dropout:
    value: 0.05
lora_r:
    value: 16
lr:
    value: 0.0001
micro_batch_size:
    value: 32
mini_train:
    value: true
num_workers:
    value: 4
output_dir:
    value: ./checkpoints
resume_from_checkpoint:
    value: false
s3_bucket:
    value: furniture-clip-dataset-v1
s3_prefix:
    value: dataset-clip/
scenario:
    value: dual_lora
seed:
    value: 42
wandb_project:
    value: clip-lr-finder
warmup_steps:
    value: 100
wd:
    value: 0.1
